import { NextRequest, NextResponse } from 'next/server';
import { getSiteById, getTokensBySiteId } from '@/lib/db';
import type { DesignToken } from '@/lib/types';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') || 'css';
    
    const site = await getSiteById(id);
    if (!site) {
      return NextResponse.json(
        { error: 'Site not found' },
        { status: 404 }
      );
    }
    
    const tokens = await getTokensBySiteId(id);
    
    let output: string;
    let contentType: string;
    let filename: string;
    
    switch (format) {
      case 'json':
        output = exportToJSON(tokens, site.domain);
        contentType = 'application/json';
        filename = `${site.domain}-tokens.json`;
        break;
      case 'tailwind':
        output = exportToTailwind(tokens, site.domain);
        contentType = 'application/javascript';
        filename = `${site.domain}-tailwind.config.js`;
        break;
      case 'css':
      default:
        output = exportToCSS(tokens, site.domain);
        contentType = 'text/css';
        filename = `${site.domain}-tokens.css`;
        break;
    }
    
    return new NextResponse(output, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Failed to export tokens:', error);
    return NextResponse.json(
      { error: 'Failed to export tokens' },
      { status: 500 }
    );
  }
}

function exportToCSS(tokens: DesignToken[], domain: string): string {
  const lines = [
    `/* Design Tokens extracted from ${domain} by StyleSync */`,
    `/* Generated on ${new Date().toISOString()} */`,
    '',
    ':root {',
  ];
  
  const colorTokens = tokens.filter(t => t.category === 'color');
  const typographyTokens = tokens.filter(t => t.category === 'typography');
  const spacingTokens = tokens.filter(t => t.category === 'spacing');
  
  if (colorTokens.length > 0) {
    lines.push('  /* Colors */');
    for (const token of colorTokens) {
      lines.push(`  --${token.name}: ${token.value};`);
    }
    lines.push('');
  }
  
  if (typographyTokens.length > 0) {
    lines.push('  /* Typography */');
    for (const token of typographyTokens) {
      const meta = token.metadata;
      lines.push(`  --font-${token.name}: ${token.value};`);
      if (meta.font_size) lines.push(`  --font-size-${token.name}: ${meta.font_size};`);
      if (meta.font_weight) lines.push(`  --font-weight-${token.name}: ${meta.font_weight};`);
      if (meta.line_height) lines.push(`  --line-height-${token.name}: ${meta.line_height};`);
    }
    lines.push('');
  }
  
  if (spacingTokens.length > 0) {
    lines.push('  /* Spacing */');
    for (const token of spacingTokens) {
      lines.push(`  --${token.name}: ${token.value};`);
    }
  }
  
  lines.push('}');
  
  return lines.join('\n');
}

function exportToJSON(tokens: DesignToken[], domain: string): string {
  const organized: Record<string, Record<string, { value: string; metadata: Record<string, unknown> }>> = {
    colors: {},
    typography: {},
    spacing: {},
  };
  
  for (const token of tokens) {
    const category = token.category === 'color' ? 'colors' : token.category;
    organized[category][token.name] = {
      value: token.value,
      metadata: token.metadata,
    };
  }
  
  return JSON.stringify({
    $schema: 'https://stylesync.dev/schema/tokens.json',
    name: `${domain} Design Tokens`,
    generated: new Date().toISOString(),
    ...organized,
  }, null, 2);
}

function exportToTailwind(tokens: DesignToken[], domain: string): string {
  const colorTokens = tokens.filter(t => t.category === 'color');
  const spacingTokens = tokens.filter(t => t.category === 'spacing');
  const typographyTokens = tokens.filter(t => t.category === 'typography');
  
  const colors: Record<string, string> = {};
  for (const token of colorTokens) {
    colors[token.name] = token.value;
  }
  
  const spacing: Record<string, string> = {};
  for (const token of spacingTokens) {
    const index = token.name.replace('space-', '');
    spacing[index] = token.value;
  }
  
  const fontFamily: Record<string, string[]> = {};
  for (const token of typographyTokens) {
    fontFamily[token.name] = [token.value];
  }
  
  return `// Tailwind Config - Design Tokens from ${domain}
// Generated by StyleSync on ${new Date().toISOString()}

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 6).replace(/"/g, "'")},
      spacing: ${JSON.stringify(spacing, null, 6).replace(/"/g, "'")},
      fontFamily: ${JSON.stringify(fontFamily, null, 6).replace(/"/g, "'")},
    },
  },
};
`;
}
