import { NextRequest, NextResponse } from 'next/server';
import { getSiteById, getTokensBySiteId } from '@/lib/db';
import type { DesignTokens, ColorToken, TypographyToken, SpacingToken } from '@/lib/types';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const { searchParams } = new URL(request.url);
    const format = searchParams.get('format') || 'css';
    
    const site = await getSiteById(id);
    if (!site) {
      return NextResponse.json(
        { error: 'Site not found' },
        { status: 404 }
      );
    }
    
    const tokens = await getTokensBySiteId(id);
    if (!tokens) {
      return NextResponse.json(
        { error: 'No tokens found for this site' },
        { status: 404 }
      );
    }
    
    let output: string;
    let contentType: string;
    let filename: string;
    
    switch (format) {
      case 'json':
        output = exportToJSON(tokens, site.domain);
        contentType = 'application/json';
        filename = `${site.domain}-tokens.json`;
        break;
      case 'tailwind':
        output = exportToTailwind(tokens, site.domain);
        contentType = 'application/javascript';
        filename = `${site.domain}-tailwind.config.js`;
        break;
      case 'css':
      default:
        output = exportToCSS(tokens, site.domain);
        contentType = 'text/css';
        filename = `${site.domain}-tokens.css`;
        break;
    }
    
    return new NextResponse(output, {
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error('Failed to export tokens:', error);
    return NextResponse.json(
      { error: 'Failed to export tokens' },
      { status: 500 }
    );
  }
}

function exportToCSS(tokens: DesignTokens, domain: string): string {
  const lines = [
    `/* Design Tokens extracted from ${domain} by StyleSync */`,
    `/* Generated on ${new Date().toISOString()} */`,
    '',
    ':root {',
  ];
  
  // Colors
  if (tokens.colors) {
    lines.push('  /* Colors */');
    for (const [category, colorTokens] of Object.entries(tokens.colors)) {
      if (Array.isArray(colorTokens)) {
        colorTokens.forEach((token: ColorToken, index: number) => {
          const name = `color-${category}-${index}`;
          lines.push(`  --${name}: ${token.value};`);
        });
      }
    }
    lines.push('');
  }
  
  // Typography
  if (tokens.typography) {
    lines.push('  /* Typography */');
    for (const [category, typographyTokens] of Object.entries(tokens.typography)) {
      if (Array.isArray(typographyTokens)) {
        typographyTokens.forEach((token: TypographyToken, index: number) => {
          const name = `font-${category}-${index}`;
          lines.push(`  --${name}-family: ${token.fontFamily};`);
          lines.push(`  --${name}-size: ${token.fontSize};`);
          lines.push(`  --${name}-weight: ${token.fontWeight};`);
          lines.push(`  --${name}-line-height: ${token.lineHeight};`);
        });
      }
    }
    lines.push('');
  }
  
  // Spacing
  if (tokens.spacing?.values) {
    lines.push('  /* Spacing */');
    tokens.spacing.values.forEach((token: SpacingToken, index: number) => {
      lines.push(`  --space-${index}: ${token.value};`);
    });
  }
  
  lines.push('}');
  
  return lines.join('\n');
}

function exportToJSON(tokens: DesignTokens, domain: string): string {
  return JSON.stringify({
    $schema: 'https://stylesync.dev/schema/tokens.json',
    name: `${domain} Design Tokens`,
    generated: new Date().toISOString(),
    colors: tokens.colors || {},
    typography: tokens.typography || {},
    spacing: tokens.spacing || {},
  }, null, 2);
}

function exportToTailwind(tokens: DesignTokens, domain: string): string {
  const colors: Record<string, string> = {};
  const spacing: Record<string, string> = {};
  const fontFamily: Record<string, string[]> = {};
  
  // Flatten colors
  if (tokens.colors) {
    for (const [category, colorTokens] of Object.entries(tokens.colors)) {
      if (Array.isArray(colorTokens)) {
        colorTokens.forEach((token: ColorToken, index: number) => {
          colors[`${category}-${index}`] = token.value;
        });
      }
    }
  }
  
  // Flatten spacing
  if (tokens.spacing?.values) {
    tokens.spacing.values.forEach((token: SpacingToken, index: number) => {
      spacing[String(index)] = token.value;
    });
  }
  
  // Flatten typography
  if (tokens.typography) {
    for (const [category, typographyTokens] of Object.entries(tokens.typography)) {
      if (Array.isArray(typographyTokens)) {
        typographyTokens.forEach((token: TypographyToken, index: number) => {
          fontFamily[`${category}-${index}`] = [token.fontFamily];
        });
      }
    }
  }
  
  return `// Tailwind Config - Design Tokens from ${domain}
// Generated by StyleSync on ${new Date().toISOString()}

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 6).replace(/"/g, "'")},
      spacing: ${JSON.stringify(spacing, null, 6).replace(/"/g, "'")},
      fontFamily: ${JSON.stringify(fontFamily, null, 6).replace(/"/g, "'")},
    },
  },
};
`;
}
